[package]
name = "fake-data"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", default-features = false }
dialoguer = "0.11.0"
fake = { version = "4.3.0", features = [
  "always-true-rng",
  "base64",
  "bigdecimal",
  "bigdecimal-rs",
  "bson",
  "bson_oid",
  "chrono",
  "chrono-tz",
  "cli",
  "derive",
  "dummy",
  "email_address",
  "geo",
  "geo-types",
  "glam",
  "http",
  "indexmap",
  "maybe-non-empty-collections",
  "num-traits",
  "rand_core",
  "random_color",
  "rust_decimal",
  "semver",
  "serde_json",
  "time",
  "ulid",
  "url",
  "url-escape",
  "uuid",
  "zerocopy",
] }

[build-dependencies]
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"] }
